name: Build and deploy to public Azure feed
on:
  workflow_dispatch:
env:
  NUGET_PACKAGE_PATH: ./published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: .
  PS_SOURCE_URL: "https://raw.githubusercontent.com/jsorling/miscscripts/main/github/actions"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Set build info
      run: '& iex ((New-Object System.Net.WebClient).DownloadString("$env:PS_SOURCE_URL/buildinfo.ps1"))'
      shell: pwsh
    - name: Create nuget.config
      run: dotnet new nugetconfig
    - name: Set nuget add azure public feed
      run: >
        dotnet nuget add
        source https://pkgs.dev.azure.com/sorling/PublicFeed/_packaging/PublicFeed/nuget/v3/index.json
        -n azurepublic
        --configfile nuget.config
    - name: Pack
      run: >
        dotnet pack
        src/sqlexecMetaLib/sqlexecMetaLib.csproj
        --configuration ${{ env.CONFIGURATION }}
        --output "${{ env.NUGET_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nugetpkg
        path: ${{ env.NUGET_PACKAGE_PATH }}
  deploy:
  # https://learn.microsoft.com/en-us/azure/devops/artifacts/quickstarts/github-actions?view=azure-devops
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: nugetpkg
        path: ${{ env.NUGET_PACKAGE_PATH }}
    - name: Create nuget.config
      run: dotnet new nugetconfig      
    - name: Set nuget add azure public feed
      run: >
        dotnet nuget add
        source https://pkgs.dev.azure.com/sorling/PublicFeed/_packaging/PublicFeed/nuget/v3/index.json
        -n azurepublic
        --configfile nuget.config
        -u jsorling
        -p ${{ secrets.azpublicfeedpat }}
        --store-password-in-clear-text
    - name: Push nuget
      run: >
        dotnet nuget push
        "${{ env.NUGET_PACKAGE_PATH }}/**/*.nupkg"
        --source azurepublic
        --api-key AZ
